### PR TITLE
Auth with pundit

### PR DESCRIPTION
**Pull request by melo616**

### CODE REVIEW

**Review by armstrca — APPROVED** [review]

**Review by aldoportillo — COMMENTED** [review]
Looks good. Good job!

**Review by armstrca — COMMENTED** [review]
Looks great. Молодчина!

**Review by carmanchiu — COMMENTED** [review]
good stuff 😎

**Comment by Dantexkilljoy** [comment]
Looks good! Blame Calvin for merging it.

**Pull request merged**
